query userLastOrder {
  userLastOrder {
    orderId
    value
    items {
      uniqueId
      id
      name
      sellingPrice
      imageUrl
      detailUrl
      quantity
      parentItemIndex
      parentAssemblyBinding
      seller
      additionalInfo {
        brandName
      }
    }
    totals {
      id
      name
      value
    }
  }
}
